// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reon!");

var lamp = "one";

var lamp_1 = "one";

var some_value = /* () */0;

exports.some_value = some_value;
exports.lamp = lamp;
exports.lamp_1 = lamp_1;
/*  Not a pure module */
