// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_oo_curry = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var shared = [
  "name",
  "eyecolor"
];

console.log("Hello, BuckleScript and Reon!");

var lamp = "one";

var lamp_1 = "one";

var oderTim = /* record */[
  /* name */"Tim",
  /* age */53
];

var evenOlderTim = /* record */[
  /* name */"Tim",
  /* age */53
];

var lion = /* record */[
  /* species */"Lion",
  /* scary */true
];

lion[/* scary */1] = false;

var $$class = CamlinternalOO.create_table(shared);

var ids = CamlinternalOO.get_method_labels($$class, shared);

var name = ids[0];

var eyecolor = ids[1];

CamlinternalOO.set_methods($$class, /* array */[
      name,
      (function (self$1) {
          return "Anna";
        }),
      eyecolor,
      (function (self$1) {
          return "brown";
        })
    ]);

CamlinternalOO.init_class($$class);

var anna = CamlinternalOO.create_object_opt(0, $$class);

Caml_oo_curry.js1(-453768622, 1, anna);

var myItem = /* Todo */Block.__(1, [
    "redesign website",
    false
  ]);

var message;

if (myItem.tag) {
  var text = "redesign website";
  message = text === "redesign website" ? "Matche value" : "Here is your todo: " + (text + Pervasives.string_of_bool(false));
} else {
  message = "Here is your noteredesign website";
}

var response = /* Success */[/* record */[
    /* id */5,
    /* name */"Artem",
    /* age */45
  ]];

var ui = typeof response === "number" ? (
    response !== 0 ? "Something went wrong!" : "Request is loading now!"
  ) : "Your name is: Artem";

var meaningfulValue = "42";

var meaningfulResult = meaningfulValue !== undefined ? "Current value: " + meaningfulValue : "This is none value";

var some_value = /* () */0;

var person = /* record */[
  /* name */"Anna",
  /* age */28
];

var tim = /* record */[
  /* name */"Tim",
  /* age */52
];

var timsName = "Tim";

var timsAge = 52;

var name$1 = "Tim";

var olderTim = /* record */[
  /* name */"Tim",
  /* age */53
];

var isReasonGreat = /* Maybe */2;

var state = /* Loading */0;

exports.some_value = some_value;
exports.lamp = lamp;
exports.lamp_1 = lamp_1;
exports.person = person;
exports.tim = tim;
exports.timsName = timsName;
exports.timsAge = timsAge;
exports.name = name$1;
exports.oderTim = oderTim;
exports.olderTim = olderTim;
exports.evenOlderTim = evenOlderTim;
exports.lion = lion;
exports.anna = anna;
exports.isReasonGreat = isReasonGreat;
exports.myItem = myItem;
exports.message = message;
exports.state = state;
exports.response = response;
exports.ui = ui;
exports.meaningfulValue = meaningfulValue;
exports.meaningfulResult = meaningfulResult;
/*  Not a pure module */
