// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Math$MyNewProject = require("./Math.bs.js");

Pervasives.print_int(Math$MyNewProject.add(1, 2));

console.log("");

Pervasives.print_float(Math$MyNewProject.pi);

console.log("");

/*  Not a pure module */
