// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var mutable_value = /* record */[/* contents */6];

mutable_value[0] = 8;

var store = /* record */[/* contents : Menu */0];

store[0] = /* GameOver */2;

store[0] = /* Playing */1;

List.find((function (x) {
        return x > 1;
      }), /* [] */0);

try {
  throw Caml_builtin_exceptions.not_found;
}
catch (exn){
  if (exn !== Caml_builtin_exceptions.not_found) {
    throw exn;
  }
  
}

var exit = 0;

var item;

try {
  item = List.find((function (x) {
          return x > 1;
        }), /* [] */0);
  exit = 1;
}
catch (exn$1){
  if (exn$1 !== Caml_builtin_exceptions.not_found) {
    throw exn$1;
  }
  
}

if (exit === 1) {
  "Here is your item " + String(item);
}

var exit$1 = 0;

var item$1;

try {
  item$1 = List.find((function (x) {
          return x > 1;
        }), /* :: */[
        42,
        /* [] */0
      ]);
  exit$1 = 1;
}
catch (exn$2){
  if (exn$2 !== Caml_builtin_exceptions.not_found) {
    throw exn$2;
  }
  
}

if (exit$1 === 1) {
  "Here is your item " + String(item$1);
}

var InputClosed = Caml_exceptions.create("Other-MyNewProject.InputClosed");

throw [
      InputClosed,
      "Error!"
    ];

exports.mutable_value = mutable_value;
exports.store = store;
exports.InputClosed = InputClosed;
exports.x = x;
/*  Not a pure module */
