// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var coord_1 = /* tuple */[
  10,
  20
];

var coord_2 = /* tuple */[
  2.3,
  4.4
];

var ship_1 = /* record */[
  /* name */"John",
  /* age */52
];

exports.coord_1 = coord_1;
exports.coord_2 = coord_2;
exports.ship_1 = ship_1;
/* No side effect */
